### ISSUE TITLE
Improve the pets listing page

### ISSUE THREAD

**Issue by shwetakanekar** [PratyayDhond/Pet-shop-website#4]
Hi, I wanted to work on improving the pets listing page. 

At present the page looks like this:
![image](https://github.com/PratyayDhond/Pet-shop-website/assets/76559918/6df6261e-67c0-4109-8bdc-6c58ac9f81b7)

I wanted to fix below issues:
1. The content in the cards is overflowing. Organize the content so that it fits in the card.
2. Last 3 cards have same content. Update 2 of those cards with different content.

Please assign me this issue if I can proceed with the changes.

**Comment by PratyayDhond** [comment]
Sure @shwetakanekar  go ahead!
