### ISSUE TITLE
[bug]/page title does not reflect page content

### ISSUE THREAD

**Issue by aryan8180** [PratyayDhond/Pet-shop-website#6]
### **Description:**

I have noticed that the About page is titled "Document". While checking the Dogs page, the title got renamed as "Pet Store". 
(Example: The title format for it can be "Website Name: Page we are on." in this case "Bark Park: About Us" or simply "About Us".

### **Steps to Reproduce:**

1. When on homepage, click on "About", present in the navigation bar.
2. The redirected page will be showing the page titled as "Document".
3. If navigated to "Supplies" from navigation bar, it displayed the title to "PET STORE".
4. The same title is been given to "Dogs" page.

### **Expected Behaviour:**

- The title of a page should provide a clear indication of the content that users will find when they access the page.

### **Additional Information:**
![title_doc](https://github.com/PratyayDhond/Pet-shop-website/assets/86112346/564958a0-60a0-469d-9b76-b549bafdefd7)
This is the title of the page when navigated to the About page.

**Comment by OmPat1l** [comment]
Resolved, check the latest commit
